---
apiVersion: experimental.kpack.pivotal.io/v1alpha1
kind: Stack
metadata:
  name: bionic-stack
  namespace: kpack
spec:
  id: "io.buildpacks.stacks.bionic"
  buildImage:
    image: "cloudfoundry/build:0.0.23-full-cnb"
  runImage:
    image: "cloudfoundry/run:0.0.23-full-cnb"
