apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: wavefront-proxy
    name: wavefront-proxy
  name: wavefront-proxy
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wavefront-proxy
  template:
    metadata:
      labels:
        app: wavefront-proxy
    spec:
      containers:
        - name: wavefront-proxy
          image: wavefronthq/proxy:5.7
          imagePullPolicy: IfNotPresent
          env:
            - name: WAVEFRONT_URL
              value: 'https://<WAVEFRONT_DOMAIN>.wavefront.com/api/'
            - name: WAVEFRONT_TOKEN
              value: '<WAVEFRONT_TOKEN>'
            # Zipkin Tracing Environment Variable
            - name: WAVEFRONT_PROXY_ARGS
              value: '--traceZipkinListenerPorts 9411'
          ports:
            - containerPort: 2878
              protocol: TCP
            # Zipkin Tracing Port
            - containerPort: 9411
              protocol: TCP
          securityContext:
            privileged: false
---
apiVersion: v1
kind: Service
metadata:
  name: wavefront-proxy
  labels:
    app: wavefront-proxy
  namespace: default
spec:
  ports:
    - name: wavefront
      port: 2878
      protocol: TCP
    - name: zipkin
      port: 9411
      protocol: TCP
  selector:
    app: wavefront-proxy