apiVersion: build.pivotal.io/v1alpha1
kind: Image
metadata:
  name: account-service
  namespace: kpack
spec:
  tag: dhubau/account-service
  serviceAccount: kpack-service-account
  successBuildHistoryLimit: 2
  builder:
    name: default-builder
    kind: Builder
  cacheSize: "2Gi"
  source:
    git:
      url: https://github.com/Turbots/tanzu-demo.git
      revision: master
    subPath: "account-service"