apiVersion: build.pivotal.io/v1alpha1
kind: Image
metadata:
  name: payment-service
  namespace: kpack
spec:
  tag: dhubau/payment-service
  serviceAccount: kpack-service-account
  builder:
    name: custom-java-builder
    kind: CustomBuilder
  cacheSize: "2Gi"
  source:
    git:
      url: https://github.com/Turbots/tanzu-demo.git
      revision: master
    subPath: "payment-service"