apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: rabbit
spec:
  destination:
    namespace: default
    server: 'https://dev.beijing.cf-app.com:8443'
  source:
    repoURL: 'https://charts.bitnami.com/bitnami'
    targetRevision: 6.25.9
    chart: rabbitmq
    helm:
      parameters:
      - name: replicas
        value: "2"
  project: default
  syncPolicy:
    automated:
      automated:
        prune: false
        selfHeal: false
      prune: true
      selfHeal: true
