apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: rabbit
spec:
  destination:
    server: 'DEV_CLUSTER_URL'
    namespace: WORKLOAD_NAMESPACE
  source:
    repoURL: 'https://charts.bitnami.com/bitnami'
    targetRevision: 6.25.9
    chart: rabbitmq
    helm:
      parameters:
      - name: replicas
        value: "2"
      - name: service.type
        value: "LoadBalancer"
      - name: rabbitmq.existingPasswordSecret
        value: rabbit
      - name: rabbitmq.existingErlangSecret
        value: rabbit
      - name: forceBoot.enabled
        value: true
  project: default
  syncPolicy:
    automated:
      automated:
        prune: false
        selfHeal: false
      prune: true
      selfHeal: true
