apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: wavefront-proxy-ENVIRONMENT
spec:
  destination:
    server: 'CLUSTER_URL'
    namespace: WORKLOAD_NAMESPACE
  source:
    repoURL: 'https://github.com/Turbots/tanzu-demo-gitops'
    targetRevision: master
    path: 'ENVIRONMENT/wavefront-proxy'
  project: ENVIRONMENT
  syncPolicy:
    automated:
      automated:
        prune: false
        selfHeal: false
      prune: true
      selfHeal: true
