apiVersion: v1
kind: Secret
metadata:
  name: dockerhub-creds
  namespace: kpack
  annotations:
    build.pivotal.io/docker: https://index.docker.io/v1/
type: kubernetes.io/basic-auth
stringData:
  username: <username>
  password: <password>
