---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: confirmation-service
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: confirmation-service
  template:
    metadata:
      labels:
        app: confirmation-service
    spec:
      containers:
        - name: confirmation-service
          image: docker.io/dhubau/confirmation-service:latest
          imagePullPolicy: Always
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: SPRING_RABBITMQ_HOST
              value: rabbit-rabbitmq
            - name: SPRING_RABBITMQ_USERNAME
              value: user
            - name: SPRING_RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbit-rabbitmq
                  key: rabbitmq-password
            - name: MANAGEMENT_METRICS_EXPORT_WAVEFRONT_ENABLED
              value: 'true'
            - name: MANAGEMENT_METRICS_EXPORT_WAVEFRONT_URI
              value: 'https://surf.wavefront.com'
            - name: MANAGEMENT_METRICS_EXPORT_WAVEFRONT_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: wavefront
                  key: token
          resources:
            requests:
              memory: 1024Mi
              cpu: 500m
            limits:
              memory: 1024Mi
          ports:
            - containerPort: 8080